export const CLEAR = 'CLEAR'
export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN'
export const SET_TRIPS = 'SET_TRIPS'
export const SET_TASKS = 'SET_TASKS'
export const TOGGLE_LOADING = 'TOGGLE_LOADING'
export const TOGGLE_TASK = 'TOGGLE_TASK'
