export const CLEAR_TASK_FORM = 'CLEAR_TASK_FORM'
export const DELETE_TASK = 'DELETE_TASK'

export const EDIT_TASK = 'EDIT_TASK'

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES'
export const FETCH_CURRENCIES = 'FETCH_CURRENCIES'
export const FETCH_EXPENSES = 'FETCH_EXPENSES'
export const FETCH_PLACES = 'FETCH_PLACES'
export const FETCH_REMAINING_AMOUNT_PER_SOURCE = 'FETCH_REMAINING_AMOUNT_PER_SOURCE'
export const FETCH_SPENT_PER_SOURCE = 'FETCH_SPENT_PER_SOURCE'
export const FETCH_SPENT_PER_CATEGORY = 'FETCH_SPENT_PER_CATEGORY'
export const FETCH_SPENT_PER_DAY = 'FETCH_SPENT_PER_DAY'
export const FETCH_SOURCES = 'FETCH_SOURCES'
export const FETCH_TASKS = 'FETCH_TASKS'
export const FETCH_TRIPS = 'FETCH_TRIPS'

export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'

export const SAVE_TASK = 'SAVE_TASK'

export const TOGGLE_TASK = 'TOGGLE_TASK'
